version: '3.8'

services:
  superbch:
    build: .
    command: start --skip-sanity-check=true
    ports:
      - "8545:8545"
    restart: always
    volumes:
      - superbch_data:/root/.superbchd
volumes:
    superbch_data:
