# This is a basic workflow to help you get started with Actions


# https://github.com/actions/cache
# https://github.com/golangci/golangci-lint-action

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        go: [ 1.18.x ]
        os: [ ubuntu-latest ]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install gcc-8 g++-8
          sudo apt install libgflags-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
          sudo apt install libsnappy-dev

      - name: Cache rocksdb
        id: cache-rocksdb
        uses: actions/cache@v2
        with:
          path: rocksdb-5.18.4
          key: ${{ runner.os }}-rocksdb-5.18.4-static2

      - name: Build rocksdb
        if: steps.cache-rocksdb.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/facebook/rocksdb/archive/refs/tags/v5.18.4.tar.gz
          tar zxvf v5.18.4.tar.gz
          cd rocksdb-5.18.4
          make EXTRA_CXXFLAGS="-march=x86-64" CC=gcc-8 CXX=g++-8 static_lib

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout superBCH
        uses: actions/checkout@v2
        with:
          path: superbch

      - name: Checkout moeingevm
        uses: actions/checkout@v2
        with:
          repository: superbch/moeingevm
          path: moeingevm

      - name: Build evmwrap
        run: |
          cd moeingevm/evmwrap
          make

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build & Test superBCH
        run: |
          export ROCKSDB_PATH="$PWD/rocksdb-5.18.4"
          export CGO_CFLAGS="-I$ROCKSDB_PATH/include"
          export CGO_LDFLAGS="-L$ROCKSDB_PATH -L$PWD/moeingevm/evmwrap/host_bridge/ -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd"
          cd superbch
          go version
          go build ./...
          go test -tags params_testnet -coverprofile=coverage.out -covermode=atomic -p 1 ./...
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
          /home/runner/go/bin/golangci-lint run
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)